### ISSUE TITLE
[1.15.2] current version hard coded to 1.15.1

### ISSUE THREAD

**Issue by ProsperCraft** [ldtteam/Performant#11]
https://gist.github.com/ProsperCraft/7e41db1a6f11f9367dc36829f6121aa3

**Comment by someaddons** [comment]
removed in 1.7 :)

**Comment by ProsperCraft** [comment]
Works great, here are some new screenshots for you :)

![pre-performant](https://user-images.githubusercontent.com/4427684/73960249-c5a77800-48c7-11ea-89c1-a232a50716df.png)

Post Performant- 
![image](https://user-images.githubusercontent.com/4427684/73960271-cdffb300-48c7-11ea-9c31-763463c87c02.png)

**Comment by ProsperCraft** [comment]
Both taken during daytime.

**Comment by someaddons** [comment]
I like those screenshots :) 
52ms ticktime is still a little bit laggy though, guess the server is a bit crowded or some mod causes lags. Incase you don't know this one yet: https://github.com/lucko/spark is an amazing profiler for identifying lag, feel free to send me a report to look at if you want :D
