### ISSUE TITLE
Crash with Fish's Undead Rising mod

### ISSUE THREAD

**Issue by V-Boy** [ldtteam/Performant#13]
**Describe the bug**
Spawned some mobs in from Fish's Undead Rising, crash happened
**To Reproduce**
Spawn in fish's undead mobs

**Expected behavior**
The game not to crash
**Screenshots**

** Mod version **
Your mods version
Performant=1.7
Fish's=1.0.13

** Logs **
Latest/Crash log
https://paste.dimdev.org/hojocodelu.mccrash

**Comment by someaddons** [comment]
fixed in 1.8
