### ISSUE TITLE
Nether loading bug

### ISSUE THREAD

**Issue by V-Boy** [ldtteam/Performant#14]
**Describe the bug**
The nether world will freeze when you have Primtive Mobs, world won't generate any further
**To Reproduce**
1. Load up MC with Primitive Mobs and its library Multimob, and performant
2. Enter the nether
3. Move around
4. Notice how nothing is loading and the world is frozen

**Screenshots**

** Mod version **
Performant 1.7
Primitive Mobs 1.2.3a

** Logs **
Latest/Crash log

**Comment by someaddons** [comment]
fixed in 1.8
