### ISSUE TITLE
Crash with Dynamic Surroundings

### ISSUE THREAD

**Issue by V-Boy** [ldtteam/Performant#16]
**Describe the bug**
When you have Dynamic Surroundings loaded up with performant, MC won't stop

**To Reproduce**
1. Download latest version of performant and dynamic surroundings with its dependencies
2. load up minecraft
3. within the first few seconds it wont work

**Expected behavior**
to load up minecraft

**Screenshots**

** Mod version **
Performant 1.8
DynamicSurroundings-1.12.2-3.6.0.2.jar
OreLib-1.12.2-3.6.0.1.jar

** Logs **
Latest/Crash log
debug: https://hastebin.com/azedotomow.md
latest: https://hastebin.com/usejakuxoh.md

**Comment by someaddons** [comment]
dynamic surrounding is using old mixins, wont work with performant
