### ISSUE TITLE
[1.12.2] my game simply don't launch bcs of your mo

### ISSUE THREAD

**Issue by Zack7292** [ldtteam/Performant#17]
**Describe the bug**
when i launch my game it don't work.

**To Reproduce**
lunch yur game

**Expected behavior**
my game to be launched

** Mod version **
latest

here the pack: https://www.mediafire.com/file/wlhucmfsp1dfv32/Infex_pack_1.12.2.zip/file
that is so you know what mod cause this with yours :)

**Comment by someaddons** [comment]
try the 1.7 version if 1.8/1.9 doesnt work, some mods still havent update mixin.
