### ISSUE TITLE
Broken configuration file

### ISSUE THREAD

**Issue by Leeo97one** [ldtteam/Performant#18]
**Describe the bug**
The configuration file `performant-common.toml` seems a bit broken.

**To Reproduce**
1. Launch the game to generate the default configuration.
2. Observe the content of `config/performant-common.toml`.

**Expected behavior**
A configuration file without `[Entity.Entity.Entity....`.

**Mod version**
1.15-1.7

**Logs and config file**
https://gist.github.com/Leeo97one/505b1119bb13704625c63650f9020e47

**Comment by Leeo97one** [comment]
I hope at least that it's only a "visual issue" and it does not affect the mod behavior.

**Comment by someaddons** [comment]
its only visual

**Comment by Leeo97one** [comment]
OK thanks, good to know! So it's a know bug?

**Comment by someaddons** [comment]
ye gonna be fixed in the next update

**Comment by someaddons** [comment]
fixed in 1.8
