### ISSUE TITLE
[1.15.2]Server crash

### ISSUE THREAD

**Issue by EnterFor** [ldtteam/Performant#19]
I don't know why,
Because I don't know whose problem it is.
Colony or Performant? I don't know. Can you help me
[crash-2020-03-27_20.16.29-server.txt](https://github.com/ldtteam/Performant/files/4393658/crash-2020-03-27_20.16.29-server.txt)
[debug.log](https://github.com/ldtteam/Performant/files/4393666/debug.log)

**Comment by someaddons** [comment]
thats a minecolonies crash, upgrade to the latest alpha and report there if its still crashing
