### ISSUE TITLE
Crashes with Mobs and Hoppers

### ISSUE THREAD

**Issue by supersaiyansubtlety** [ldtteam/Performant#2]
It looks like this mod makes it so hoppers try to collect mobs. 
Here's a crash log, this was the only mod installed, I generated a fresh world, placed a hopper, spawned a chicken, and pushed it on top of the hopper, then the game crashed. 
[performant-puts-chickens-in-hoppers.txt](https://pastebin.com/43zXd97A)

**Comment by someaddons** [comment]
ye its the experimental feature which has some bugs, might want to disable it in the config. Gonna change that soon

**Comment by someaddons** [comment]
Fixed in 1.5
