### ISSUE TITLE
[1.15.2] Server Crashes on startup

### ISSUE THREAD

**Issue by ocram9** [ldtteam/Performant#20]
**Describe the bug**
When the server starts it almost immediately crashes.

**To Reproduce**
1. Start server with performant 1.10
2. Server crashes

** Versions **
performant v.1.10
Minecraft 1.15.2
Forge 31.1.30

** Logs **
https://gist.github.com/ocram9/87eca6b3e4db1e76d2513f201fe12a6b

**Comment by someaddons** [comment]
should be fixed in 1.11
