### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by waddon1** [ldtteam/Performant#21]
**Describe the bug**
The game crashes on startup since version 1.10

**To Reproduce**
1. Start game with Performant 1.10
2. Game crashes

** Mod version **
Performant 1.10
Minecraft 1.15.2
Forge 31.1.30

** Logs **
https://gist.github.com/waddon1/08655c8d14522e6341f670d7a3310cb9

**Comment by someaddons** [comment]
should be fixed with 1.11
