### ISSUE TITLE
[1.15.2]I didn't have this problem before

### ISSUE THREAD

**Issue by EnterFor** [ldtteam/Performant#23]
**Describe the bug**
I don't know if it caused it

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/10114685/78455208-816e0380-76cf-11ea-8d60-55571ba526df.png)

** Mod version **
performant-1.15-1.12

https://spark.lucko.me/#XUMu0pTkXa

**Comment by someaddons** [comment]
its the entities AI doing some heavy pathing work, your lag would be a lot worse without performant
