### ISSUE TITLE
[1.15.2] Nether portal not working

### ISSUE THREAD

**Issue by ocram9** [ldtteam/Performant#24]
**Describe the bug**
When I enter a nether portal it doesn't teleport me, it gets stuck in the teleport animation loop.

**To Reproduce**
1. Create a nether portal
2. Try to go through it

**Versions**
Minecraft 1.15.2
performant-1.15-2.0m
Forge 31.1.37

**Comment by someaddons** [comment]
hm thats an interesting bug :D

**Comment by ocram9** [comment]
It sure is :P Are you able to replicate it, or should I quickly make a video showing it?

**Comment by someaddons** [comment]
hm in singleplayer it works

**Comment by someaddons** [comment]
oh nvm it doesnt in survival

**Comment by someaddons** [comment]
should be fixed in 2.01m
