### ISSUE TITLE
[1.15.2] Crouching does not prevent falling off blocks

### ISSUE THREAD

**Issue by AndreiTS** [ldtteam/Performant#26]
Minecraft 1.15.2
Forge 31.1.35
MixinBootstrap-1.0.2.jar
performant-1.15-2.02m.jar

It affects singleplayer/multiplayer. I also tested in survival/creative and adventure modes

**Comment by FynnWaelsing** [comment]
I had the same issue with the same version. It's not that you can't sneak necessarily, 'cause the player does crouch and move more slowly. But you can walk straight off the edge of blocks while sneaking, as I discovered to my detriment.

**Comment by Sunekaer** [comment]
Can confirm this issue we also have this issue in the FTB Omnia pack, have tested with only performant and can confirm the issue.
No errors in the log.

**Comment by someaddons** [comment]
ye gonna be fixed in the next version I'm uploading later

**Comment by someaddons** [comment]
fixed in 2.03
