### ISSUE TITLE
[1.15.2] View bobbing visual glitch

### ISSUE THREAD

**Issue by ocram9** [ldtteam/Performant#27]
**Describe the bug**
When view bobbing is enabled the walking animation is glitched (see video).

**To Reproduce**
1. Turn on view bobbing in video settings
2. Start walking

**Video**
https://www.youtube.com/watch?v=tORV0iaiReE

**Versions**
performant-1.15-2.03m
Minecraft 1.15.2
Forge 31.1.39

**Comment by waddon1** [comment]
Also experiencing this

**Comment by Pannoniae** [comment]
Me too.

**Comment by Fastfingered** [comment]
bump

**Comment by someaddons** [comment]
should be fixed in 2.04m
