### ISSUE TITLE
[1.15.2] Bouncing on bed glitch

### ISSUE THREAD

**Issue by Exarchai** [ldtteam/Performant#28]
**Describe the bug**
With this mod and mixin bootstrap installed, whenever I stand on or lie in a bed, my character (and other mobs as well) jump up and down on the bed. Villagers are also kicked out of bed as they try to lie in it.

**To Reproduce**
1. Lie in bed
2. See glitch

** Mod version **
performant-1.15-2.04m
Forge 31.1.44

**Comment by someaddons** [comment]
yea noticed that aswell xD gonna be fixed in next

**Comment by someaddons** [comment]
should be fixed in 2.05m
