### ISSUE TITLE
Bell and Shulker Box Movement Glitch

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/Performant#29]
**Describe the bug**
Both Shulker Boxes and Bells have shaky movement on my server. Other blocks could be affected.

**To Reproduce**
1. Right click the Bell
2. Open the Shulker box

**Expected behavior**
Movement of the Bell and Shulker Boxes should be smooth.

** Mod version **
`v2.04m`

**Comment by someaddons** [comment]
what exactly do you mean with shaky movement? when trying it it looks just normal. Is it the visuals?

**Comment by WenXin20** [comment]
Yeah, the visuals. When opening a Shulker box, it doesn't immediately open. Kinda like how the hand movement was jerky before that was fixed.
But it is possible that another mod is causing that since it's a modded server. Or maybe lag?

**Comment by someaddons** [comment]
the only thing in performant which could cause this is the Tileentity load balancing, but that'd mean that the block is lagging. Maybe when someone is already on low fps it can happen clientside

**Comment by someaddons** [comment]
should be fixed in 2.05m
