### ISSUE TITLE
[1.15.2] End portal in overworld teleports you back to your spawnpoint

### ISSUE THREAD

**Issue by ocram9** [ldtteam/Performant#33]
**Describe the bug**
When trying to enter an end portal in the overworld you get teleported back to your bed/spawnpoint.

**To Reproduce**
1. Try to enter an end portal

**Versions**
- Minecraft 1.15.2
- Forge 31.1.46
- Performant 2.06m

**Comment by someaddons** [comment]
fixed in 2.07m
