### ISSUE TITLE
Incompatible with FutureMC

### ISSUE THREAD

**Issue by thedarkcolour** [ldtteam/Performant#35]
**Describe the bug**
Causes an IllegalAccessException when calling func_225515_ai_ (getVelocityMultiplier/getSpeedModifier) on an ItemEntity

I can't fix this on my end because your github repo doesn't show any of your Mixins.

**To Reproduce**
Install Future MC and Performant, then throw a piece of netherite equipment onto the ground.

**Expected behavior**
The item drops onto the ground and does not burn in lava.

** Mod version **
Future MC 1.0.0
Performant 2.07m

[Crash report](https://pastebin.com/zF4g4Ywk )
[Log](https://pastebin.com/vJn338TP)

**Comment by someaddons** [comment]
fixed in 2.08m
