### ISSUE TITLE
Compatibility with ImmersivePortals

### ISSUE THREAD

**Issue by Alkiasan** [ldtteam/Performant#36]
**Describe the bug**
Whenever the server rains, Players will receive extreme FPS lag, whether they have the mod clientside or not.

**To Reproduce**
1. Have both mods installed
2. Set weather to rain
3. FPS drops immensely. (60 -> 20)

**Expected behavior**
FPS not to drop.

** Mod version **
Performant 1.14.4-1.5

** Logs **
(latest.log isn't available atm, if really needed i can get it when the server is less active haha, sorry about that. But luckily, I have a screenshot of latest.log before it was overwritten. essentially, the players are spammed clientside in latest.log by this, which is what's causing the FPS drops:
![image](https://user-images.githubusercontent.com/62717881/80269574-dab2cc80-86a8-11ea-9181-d582539c2f48.png)

**Comment by someaddons** [comment]
report this to immersive portals, has nothing to do with performant, 1.14 performant only ever touches entity AI
