### ISSUE TITLE
[1.15.2] Crash trying to load or create a world

### ISSUE THREAD

**Issue by AK-Chester** [ldtteam/Performant#38]
The game crashes when I'm trying to load or create a world with my private modpack. No crashes if I remove "Performant" and it only happens since I updated to "performant-1.15-2.10m", other / older versions did and do not crash.

[crash-2020-05-06_20.28.49-server.txt](https://github.com/ldtteam/Performant/files/4588791/crash-2020-05-06_20.28.49-server.txt)

**Comment by someaddons** [comment]
I'm not seeing anything performant related in there, pretty sure its just a coincidence

**Comment by AK-Chester** [comment]
Well, "performant-1.15-2.09m.jar" works just fine with my pack, while "2.10m" crashes on world creation & world load (each and every time) - and I felt like I should report this.

No problem, though, I'll just keep using "2.09m".

**Comment by someaddons** [comment]
ok I found the cause, and gonna fix it in the next version. Though it isnt really caused by my side more on the quiver mod's modifications

**Comment by AK-Chester** [comment]
Cool, thanks a lot! Do you think I should post this in the issues section of the qui2ver mod as well then?

**Comment by someaddons** [comment]
ye you can let him know that he's breaking PlayerInventory creation without a player

**Comment by AK-Chester** [comment]
[https://github.com/Vatuu/qui2ver/issues/4]Done(url).

Thanks again!

**Comment by Vatuu** [comment]
I mean, when would you create a **Player**Inventory without a player?

**Comment by AK-Chester** [comment]
Thanks a lot for the update!

2.11m seems to work fine with qui2ver, so I guess I can close this.
