### ISSUE TITLE
[1.15.2] "fastPathFinding" setting messes up PneumaticCraft drone pathfinding

### ISSUE THREAD

**Issue by desht** [ldtteam/Performant#40]
**Describe the bug**
When the `fastPathFinding` config settings is enabled (which it is by default), PneumaticCraft drones are frequently unable to pathfind to their destination, and teleport there instead (which is their fallback if they can't find a path).

Note: I am the PneumaticCraft: Repressurized mod author.  I'd be interested to know just what `fastPathFinding` is doing.  I can't find the code in your GitHub repo offhand; I presume it's part of the coremod code.

**To Reproduce**
1. Install Performant on a server with PneumaticCraft: Repressurized
2. Run any drone with a program that requires it to path somewhere.  Pre-programmed drones like the Harvester or Collector will work here.
3. Observe as they frequently teleport, even when their path is only a few blocks of open space.
4. Restart server with `fastPathFinding` set to false
5. Observe as drones no longer have pathfinding problems.

**Expected behavior**
Drone behaviour without the mod installed, or with `fastPathFinding` set to false is expected behaviour, where they can pathfind normally.

**Screenshots**

**Mod version**
pneumaticcraft-repressurized-1.15.2-1.1.2

**Logs**
No crashes.

**Comment by someaddons** [comment]
The vanilla logic is kept intact, the only thing which is different is that it doesnt allow you to repeatedly create paths too frequently, it limits it to 1 path/sec

**Comment by desht** [comment]
Thanks - where's the code that does that?  Trying to track down exactly what it does that confuses my drones...

**Comment by someaddons** [comment]
I think it may be this part, since its ran every tick, but not sure.
https://github.com/TeamPneumatic/pnc-repressurized/blob/7560aa1125c974cb386a9ba8a13b989acd3bf5e3/src/main/java/me/desht/pneumaticcraft/common/ai/DroneAIBlockInteraction.java#L127

Its in PathNavigator#getPathToPos

**Comment by someaddons** [comment]
can you try and see if 

[performant-1.15-2.11m.zip](https://github.com/ldtteam/Performant/files/4644022/performant-1.15-2.11m.zip)
works? it got the limit disabled

**Comment by desht** [comment]
With 1.15.2-11m, I'm not seeing any drone problems.

**Comment by someaddons** [comment]
fixed
