### ISSUE TITLE
[1.15.2] goalselectorrate issue w. Mahou Tsukai

### ISSUE THREAD

**Issue by stepsword** [ldtteam/Performant#41]
Hi,

I was hoping you could shed some light (i.e. if it's just one thing, point to like a line number or something) on what the config goalselectorrate changes in the base minecraft code?

Mahou Tsukai (the mod I develop) is in ATM5 with Performant on 1.15.2 and it seems like when goalselectorrate is above 1 my fae creatures (think flies, in terms of their movement, always moving randomly while hovering off the ground) basically drop through the floor and continue downwards to the void. The other configs don't seem to affect this at all - I thought it might have been a collision issue but no such luck, as setting goalselectorrate from 4 to 1 is the only thing that fixes it.

It's strange cause I'm fairly certain the fae have collision boxes as I call setBoundingBox(posx-xsize,... posx+xsize,...) multiple times in livingTick(), just to make sure, and when they're above something that's not air, I give them upward velocity so they should basically never touch the ground. Printing this velocity with performant installed, it seems to be working correctly and the fae never actually have a negative velocity. I assumed that something which only controls AI as goalselectorrate seems like it should would not affect movement once I put that movement directly in livingTick() as opposed to in the AI tasks, but the issue seems to only be resolved by changing that value.

Sorry for the rambling. Would you be able to share what goalselectorrate does or if you have ideas about something else affected by goalselectorrate that could be causing fae to plunge through the ground?

**Comment by someaddons** [comment]
that sounds like a weird issue, the goal selector rate simply defines the rate at which non-running tasks/goals are checked wether they should start. Basically it defines how often `shouldExecute()` is called

**Comment by someaddons** [comment]
https://github.com/ldtteam/Performant/blob/version.1.14/src/main/java/com/performant/coremod/entity/ai/CustomGoalSelector.java#L289 there you can see the delay, but the entity AI shouldnt let them drop through the ground :D

**Comment by stepsword** [comment]
thanks! that's helpful - i'll walkthrough what's happening between this and my shouldexecute() and see if I can figure it out. appreciate you taking the time!

**Comment by stepsword** [comment]
I was able to figure this out - it turned out to be something weird with collision boxes not registering properly on the client. no clue why it was affected by the AI thing. thanks for your help!

**Comment by someaddons** [comment]
sounds like a weird issue, glad you figured it out :D
