### ISSUE TITLE
Loot Chests in Dungeons/Mineshafts Empty on Server

### ISSUE THREAD

**Issue by CHead2000** [ldtteam/Performant#42]
**Describe the bug**
When going to new, unopened loot chests on my server, they are completely empty. 

**To Reproduce**
Open unopened loot chest.

**Expected behavior**
I had expected to find loot in these chests, especially since I checked by copying an older version of the world to single player, and there was loot present in chests that were empty on the server. It is currently unclear if this applies to all loot chests in the world, or only loot chests in chunks that had already been generated.

**Screenshots**
N/A

** Mod version **
1.15-2.11m

** Logs **
Latest/Crash log
[2020-05-25-1.log.gz](https://github.com/ldtteam/Performant/files/4679539/2020-05-25-1.log.gz)

**Comment by someaddons** [comment]
performant does not touch loot at all
