### ISSUE TITLE
Placing block under player while maintaning right click doesn't work

### ISSUE THREAD

**Issue by uiytt** [ldtteam/Performant#44]
**Describe the bug**
If you try to jump while maintaining right click with a block, doesn't always pose the block under you. 

**To Reproduce**
1. Install forge 1.12.2 - 14.23.5.2854
2. Launch a solo world
3. Jump while trying to place block under you (maintain right click) 
4. See problem

**Expected behavior**
The block are supposed to be placed under you

** Mod version **
1.12.2-10

**Comment by someaddons** [comment]
1.12 is finished and it doesnt even remotely touch stuff which has an effect on this
