### ISSUE TITLE
Compatability issues with Mekanism  (ATM 5 pack, Ver. 2.0+)

### ISSUE THREAD

**Issue by Tiberias42** [ldtteam/Performant#46]
**Describe the bug**
Everything is lagging / surging, like the production is being throttled. No longer has constant, smooth flow of power, fluids, gases, etc.

**To Reproduce**
1.  Build any Mekanism power generation (wind, heat surrounded by lava, solar)
2.  Build up a ore tripling system (smelter, enrichment chamber, crusher, purifier + electrolytic separator)
3. Configure systems for normal use (Oxygen piped to purifier, Hydrogen piped to gas generator, Water piped to separator, power system routed to separator ONLY, gas generator routed to power ore processing system)
4.  Insert any processable ore into tripling system (1 stack Iron Ore, etc.)
5.  Watch any piece of equipment power, gas or fluid levels.  Levels should flow smoothly, with consistent, stable performance.  BUT, currently, they are spazing out & significantly hindering operational viability of the system.

**Expected behavior**
Mekanism systems should have a smooth, constant flow to the power, gas, fluids, items & thermals being generated & moved around.

** Mod version **
performant-1.15-2.11m

**Supplemental Information**

Mekanism issue ticket:  https://github.com/mekanism/Mekanism/issues/6229

ATM-5 issue ticket:  https://github.com/AllTheMods/ATM-5/issues/157

**Comment by someaddons** [comment]
That is a completly normal and intended functionality of load balancing. Once you go over the lagging threshold set in the config Performant will slow down laggy stuff(like mekanism) to prevent your world from lagging. Ofc it has the side effects that the laggy stuff is no longer working as nicely, but thats just how load balancing works. If you want to fix this you can either disable the load balancing, or ask the mod's author to improve their performance as the mod is more affected the laggier it is.

**Comment by Tiberias42** [comment]
That's the rub, Mekanism never was causing lag spikes before, it always ran well until recently.

Well, thanks anyway.  I will copy this to the other tickets soon, maybe they can figure something out.

**Comment by someaddons** [comment]
mekanism is known to be one of the major lagging mods :D

**Comment by thiakil** [comment]
How does your mod actually determine that? Can you / the mod provide numbers?

If you're basing it on past general feelings, you should consider that there have been a great deal of performance improvements for the 1.15 version (and probably pull your head out). 

And even so, the vast majority of the pipe handling occurs on a tick event, so on big servers it's probably still going to consider it "lag"

**Comment by someaddons** [comment]
I've been in close contact with ATM5 ppl which were running a server which had mekanism and huge lag problems. Sparks they took always had ~60-70% of total server tick usage from mekanism. 
Besides its pretty easy to tell how badly optimized it is when large entity mods like minecolonies with hundreds of living entities(not just TE's) uses way less cpu on bigger servers

**Comment by thiakil** [comment]
That's comparing apples and oranges.
