### ISSUE TITLE
Server Timing Out

### ISSUE THREAD

**Issue by omerbadawy11** [ldtteam/Performant#47]
**Describe the bug**
Server timing out a lot, I circled around a lot cause I wasn't sure what was the reason. Multiple sources including the sponge discord server lead me to performant, I apologize in advance if it's not performant.
Your help is appreciated!
Thank you kindly

**To Reproduce**
Happens randomly

**Expected behavior**
The server would randomly freeze and kick every player our after about 5 mins

**Screenshots**
https://media.discordapp.net/attachments/142425412096491520/727066920901410886/unknown.png
https://cdn.discordapp.com/attachments/190213573144739841/727114892552962098/unknown.png

** Mod version **
performant-1.12.2-1.10

** Logs **
https://pastebin.com/MPZJbvde Stall report from Sampler

**Comment by someaddons** [comment]
Threading issue, something is accessing the collisions from a different thread, causing the lock. Performant is only doing mainthread stuff so its some other mod doing that. Anyways 1.12 is no longer getting updates anyways

**Comment by omerbadawy11** [comment]
Would you be kind enough to let me know if you can tell which mod caused this?
Your knowledge is much better so you might have noticed something that I can go to the Dev of the responsible mod and they'd help
Thank you,
Have a great day

**Comment by someaddons** [comment]
no can't see who is doing it

**Comment by omerbadawy11** [comment]
Thank you,
Cheers
