### ISSUE TITLE
any benefits running it together with lithium?

### ISSUE THREAD

**Issue by rlesch** [ldtteam/Performant#48]
Both mods seem to adress similar things, just wondering if running both does more harn than good?

**Comment by Raycoms** [comment]
lithium steals code of this mod. So there is no benefit.

**Comment by jellysquid3** [comment]
@Raycoms Hi. I'm the author of Lithium. What code do you believe Lithium has stolen from your mod? My work is of my own, and my mod has a strict pull request policy that requires all work to be original.

Looking at these two mods, it seems like Lithium is more all-encompassing than Performant, with the only overlap being in some entity AI optimizations.
