### ISSUE TITLE
Issue with Bewitchment mod installed, brews cannot be made. 

### ISSUE THREAD

**Issue by Mizhok** [ldtteam/Performant#5]
### Expected Behavior
Supposed to only turn the water brown after a certain
time limit to allow other ingredients to be put in.

### Actual Behavior
Water instantly starts turning brown no matter what.

### Steps to Reproduce
Put mandrake into a cauldron with the proper prerequisites for a brew.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Baubles-1.5.2
bewitchment-1.12.2-0.0.21.4	
Patchouli-Patchouli-1.0-20.jar	
Performant-1.12.2-1.6.jar
forge-14.23.5.2847

issue on bewitchment github:
https://github.com/Um-Mitternacht/Bewitchment/issues/475

**Comment by someaddons** [comment]
Shouldnt be related to this mod, since it doesn't affect TE's at all

**Comment by Sunconure11** [comment]
I believe this issue may still exist. See if anything sticks out on either end, I’m trying to reduce the amount of bugs on 1.12.

**Comment by someaddons** [comment]
1.12 is old and no longer updated
