### ISSUE TITLE
(1.15.2 - 3.3m)  Crash on loading screen

### ISSUE THREAD

**Issue by dreckz** [ldtteam/Performant#51]
**Describe the bug**
Game crashes on load up

**To Reproduce**
1: Load up modpack
2: During loading screen it crashes

**Expected behavior**
The modpack should go through a load up phase, but it ends up crashing in the middle of this.

** Mod version **
1.15.2 - 3.3m

** Logs **
Latest.log:
[2020-08-01-4.log](https://github.com/ldtteam/Performant/files/5011024/2020-08-01-4.log)

Crash log:
[crash-2020-08-01_12.49.06-client.txt](https://github.com/ldtteam/Performant/files/5011021/crash-2020-08-01_12.49.06-client.txt)

**2nd pair:**
Latest:
[2020-08-01-3.log](https://github.com/ldtteam/Performant/files/5011025/2020-08-01-3.log)

Crash:
[crash-2020-08-01_12.47.53-client.txt](https://github.com/ldtteam/Performant/files/5011026/crash-2020-08-01_12.47.53-client.txt)

**Comment by someaddons** [comment]
weird, performant doesnt even appear in those calls crashing. Does it keep crashing? Which mods do you have installed?

**Comment by dreckz** [comment]
I am.  Can I PM you the modpack?  It's currently private.

**Comment by dreckz** [comment]
[crash-2020-08-01_13.29.21-client.txt](https://github.com/ldtteam/Performant/files/5011069/crash-2020-08-01_13.29.21-client.txt)

Here is another crash report.

**Comment by someaddons** [comment]
ah that log shows a better error

**Comment by someaddons** [comment]
try if that version works please

**Comment by dreckz** [comment]
Seems to be working better now!  Thank you!

**Comment by someaddons** [comment]
nice, then it was just a simple mod compat issue :) thanks for the helpful logs!
