### ISSUE TITLE
Endermen react as if in contact with water despite being in a desert biome

### ISSUE THREAD

**Issue by robertfwallis** [ldtteam/Performant#54]
**Describe the bug**
Endermen react as if in contact with water in desert biomes, whilst it's raining.

**To Reproduce**
1. Load any world
2. "/weather rain"
3. Go to a desert biome (easiest method is "/locate desert_pyramid")
4. Spawn an Enderman

**Expected behavior**
Endermen should stand still and react as if it's not raining, since... it doesn't rain in desert biomes.

**Mod version**
(Minecraft 1.15.2)
MixinBootstrap 1.0.3
Performant 3.4m

**Comment by someaddons** [comment]
fixed in 3.5

**Comment by robertfwallis** [comment]
Still seems to be occurring in Performant 3.5m.

**Comment by someaddons** [comment]
ye fixed in 3.6 now
