### ISSUE TITLE
[1.12] Inconsistent Block Placing

### ISSUE THREAD

**Issue by CobyWalters** [ldtteam/Performant#56]
Any time a player tries to place blocks where they were just at, there are inconsistencies in placement.

**1) Placing from the side** (most notable while flying) 
If you are placing into your flight path and placing too fast (letting the blocks catch up to you), this triggers some behavior where you are unable to place the next block for a second or two.

**2) Placing from the top** (most notable when jump-placing) 
When holding right click, only one block is able to be placed.

**Mod Version**
1.7 & 1.10

**Comment by someaddons** [comment]
1.12 is not getting any updates anymore

**Comment by Dimentive** [comment]
> 1.12 is not getting any updates anymore

:( Why not?
