### ISSUE TITLE
Crash when walking on redstone block and breaking it(1.15.2)

### ISSUE THREAD

**Issue by Alkiasan** [ldtteam/Performant#57]
**Describe the bug**
Game seems to crash whenever I walk onto a redstone block.
**To Reproduce**
1. Stand on redstone block
2. Crash

**Expected behavior**
Player doesn't crash when standing on the block

** Mod version **
Performant 1.15-3.4m

Crash Log:
https://gist.github.com/Alkiasan/2e474d9fa0d51e548c0711950d451c5d
This is what appears inside of latest.log when the ore is broken.
https://gist.github.com/Alkiasan/86418c4c1904849a8a555706dcf0e8f0

**Comment by someaddons** [comment]
fixed in 3.5
