### ISSUE TITLE
Crash with Dynamic Surroundings

### ISSUE THREAD

**Issue by nebelhund** [ldtteam/Performant#58]
**Minecraft Version**: 1.12.2

**Describe the bug**
Game crashes before the main window appears when this mod is enabled with dynamic surroundings

**To Reproduce**
1. Install _performant_ 1.10
2. Install _Dynamic Surroundings_ 3.6.1.0
3. Launch the game

**Expected Behavior**
I saw both this mods installed in RoTH modpack, so I thought they should be compatible. But I can't launch my game with them both. DSurrounds developer said that it may be the difference in mixin versions, as he uses the latest version, but not all developers do the same.

**Mod version**
_performant_: 1.10
_DynamicSurroundings_: 3.6.1.0

**Logs**
https://pastebin.com/L0Bz1R8c

**Comment by someaddons** [comment]
1.12 isnt updated anymore, but it uses the latest mixin
