### ISSUE TITLE
Potential Goblin Traders compatibility issue

### ISSUE THREAD

**Issue by robertfwallis** [ldtteam/Performant#59]
**Describe the bug**
Goblin Traders spawn above-ground.

**Expected behavior**
Goblin Traders spawn underground.

**Screenshots**
![image](https://user-images.githubusercontent.com/11021224/89200819-786f3f00-d5a8-11ea-931f-0565945ab24b.png)

** Mod version **
MixinBootstrap 1.0.3
Performant 3.4m
[Goblin Traders 1.2.0](https://www.curseforge.com/minecraft/mc-mods/goblin-traders)

**Comment by someaddons** [comment]
think that is fixed in 3.6
