### ISSUE TITLE
Crash for 1.12 v1.6/v1.7 when Spongeforge is not installed.

### ISSUE THREAD

**Issue by Joebo19x** [ldtteam/Performant#6]
**Describe the bug**
Server crash when installing Performant 1.12 V1.7, without having spongeforge installed.

**To Reproduce**
1. Install Performant onto FTB revelations 3.0, without having spongeforge installed.
2. Crash

**Expected behavior**
Performant 1.5 does not crash the server, didn't think sponge compat would cause issues.

** Mod version **
Performant 1.6/1.7 cause the crash, 1.5 does not.

** Logs **
Latest/Crash log
https://pastebin.com/KsCzGWc3

**Comment by someaddons** [comment]
fixed in 1.8
