### ISSUE TITLE
Potential fatal server crash to do with Performant(?)

### ISSUE THREAD

**Issue by robertfwallis** [ldtteam/Performant#60]
**Describe the bug**
Server just randomly crashed. I don't know much because I wasn't online when it happened. The log mentions 'Cow' which I can only assume is something AI-related. None of my other mods interfere with cows in any way. The server crash also for some reason duplicated the items in my friend's furnace. I'm beginning to think there may be a compatibility issue with FastFurnace.

**Mod version**
MixinBootstrap 1.0.3
Performant 3.6m

**Logs**
https://gist.github.com/robertfwallis/a9288a5c15119756515bef1a06f635b1

**Comment by someaddons** [comment]
fixed

**Comment by robertfwallis** [comment]
Awesome, I'll look into testing this soon. Will you be looking into optimising furnaces and crafting benches? I know FastFurnace and FastWorkbench exist but they seem to be very buggy with modpacks, potentially due to registry replacements.

**Comment by someaddons** [comment]
hm I could look into those blocks ye, although the vanilla ones should already be faster as performant makes recipe lookup faster
