### ISSUE TITLE
Possible crash with aquaculture

### ISSUE THREAD

**Issue by sabinoplane** [ldtteam/Performant#64]
**Describe the bug**
First of all i wanna say i'm not sure this was performant's fault, someone told me it might be though so i pass the log here just in case. it's also worth noting that i'd never gotten crashes like this before and the day of the crash i'd only installed two mods: performant and dog breeds. This crash happened after a loong way of exploring, this is the report: https://pastebin.com/mZpEJUnP
**To Reproduce**
I have no idea, to me it just happened after exploring for a long while

**Expected behavior**
Well- not a crash

**Screenshots**
crash log is in the pastebin above (and below)

** Mod version **
1.15.2 3.7m

** Logs **
https://pastebin.com/mZpEJUnP

**Comment by sabinoplane** [comment]
It happened again, this time it doesn't even seem to have anything to do with aquaculture, here's the log: https://pastebin.com/E3mfYHyc
 
will remove the mod and see if it continues crashing

**Comment by someaddons** [comment]
should be fixed

**Comment by fara99** [comment]
Happend to us again today - performant-1.15-3.9m
Stupid carp crashing our game..

[https://pastebin.com/rB90kZ11](url)

**Comment by someaddons** [comment]
interesting, its a different crash though
