### ISSUE TITLE
Performant prevents players from falling through the world/ascending above the height limit

### ISSUE THREAD

**Issue by noobanidus** [ldtteam/Performant#65]
**Describe the bug**
Generating a creative superflat world and then digging down to bedrock. Instead of falling through, you just end up standing on a flat surface.

I'm not sure if this is intentional or not. If it *is* intentional it would be great if it was configurable, as it's negatively impacting the modpack that I'm working on/the functionality of the Bumblezone dimension (see below).

**To Reproduce**
See above.

**Expected behavior**
This strongly inhibits the behaviour of the mod "Bumblezone", which requires you to dig out of the dimension to escape.

**Screenshots**
Not applicable.

** Mod version **
Minecraft: 1.15.2
Forge: 32.2.36
Mod: 3.7m

**Comment by someaddons** [comment]
no thats not intentional :D

**Comment by someaddons** [comment]
fixed

**Comment by noobanidus** [comment]
Thanks!
