### ISSUE TITLE
Crash when player is in a village (serverside) [1.15.2]

### ISSUE THREAD

**Issue by Alkiasan** [ldtteam/Performant#66]
**Describe the bug**
Server crashes whenever a player loads into a village. This crash only happens serverside, and shuts down the server immediately.

**To Reproduce**
1. Go to Village
2. server crashes.

**Expected behavior**
Server shouldn't crash.

** Mod version **
Performant 3.8m 1.15.2

** Logs **
https://gist.github.com/Alkiasan/01ea63b7fa23c26a2d279f81472e4f59

**Comment by noobanidus** [comment]
Suffering a similar issue: https://gist.github.com/noobanidus/c8626705af542adf9d0e0108a02af153

**Comment by someaddons** [comment]
should be fixed in 3.9
