### ISSUE TITLE
Compatibility between Performant and ExtendedNether's netherite armor/tools

### ISSUE THREAD

**Issue by Alkiasan** [ldtteam/Performant#67]
**Describe the bug**
Throwing "unburnable" items from the extended nether mod into lava causes the server to crash.
**To Reproduce**
1. Throw item into lava.
2. Server crash.

**Expected behavior**
Tool is thrown into lava and server doesn't crash.

** Mod version **
Performant 3.8m
ExtendedNether 3.1.3

https://gist.github.com/Alkiasan/1c587a5e72a1f75ded2130f1b09d3304

**Comment by someaddons** [comment]
Is that reproducible with/without performant? because in this log performant is only reroutes the calling to an internal class, but does no modifications

**Comment by Alkiasan** [comment]
Yeah, seems to be an issue on ExtendedNether's part. thanks
