### ISSUE TITLE
[Suggestion] More tile-entity optimizations

### ISSUE THREAD

**Issue by KubiRem** [ldtteam/Performant#69]
Hi, I would suggest more optimizations for tile-entites - mayby set them off-thread (idn if it's possible)
Btw U are master on my 1.12.2 server 130 mean tick time  (this mean about 5-7 tps) (With all performance mods. Including performant) on 1.15.2 with performant and some other ones i get 30-13 mean tick time (20 tps) with forge tps.
Best regrads KubiRemPL

**Comment by someaddons** [comment]
not updating 1.12 anymore

**Comment by KubiRem** [comment]
I know I want them for 1.15.2

**Comment by someaddons** [comment]
the problem with tileentities lag is that 95% is caused by custom mod code, and the 1.15 version already has a load balancing setting to reduce the impact of those

**Comment by KubiRem** [comment]
Ok then. But it would be cool to see something more.
