### ISSUE TITLE
1.15 version claims to require minecraft 1.14

### ISSUE THREAD

**Issue by lag42** [ldtteam/Performant#7]
**Describe the bug**
if you try to load the 1.15 version on minecraft 1.15 it will say it requires minecraft 1.14 instead of fully loading

**To Reproduce**
install the 1.15 version of the mod on forge 1.15
look at the error screen

**Expected behavior**
that you remembered to change your [mods.toml](https://github.com/ldtteam/Performant/blob/version.1.15/src/main/resources/META-INF/mods.toml) allowing it to load on the proper version

**Screenshots**
![2020-01-11 (2)](https://user-images.githubusercontent.com/22325011/72206841-0b535b00-3458-11ea-8366-60dba3115bdd.png)

** Mod version **
1.15.1-1.4

**Comment by someaddons** [comment]
oh I forgot to change the dependency version :D

**Comment by someaddons** [comment]
fixed in 1.5
