### ISSUE TITLE
Exception on collisionbox retrieval

### ISSUE THREAD

**Issue by FeikoJoosten** [ldtteam/Performant#70]
**Describe the bug**
I turned on my mob farm and got this issue after updating to version 3.8m. Before this, we were using 2.11m which didn't have this issue.

I would love to fix this issue myself, but since not all of the source code has been committed to Github. I cannot help you out.

**To Reproduce**
Unfortunately I'm not entirely sure how to reproduce this issue, but I'm guessing that you might wanna add some safety checks which'll prevent this issue.

**Expected behavior**
Performant shouldn't cause any exceptions at all.

**Screenshots**
N/A

**Mod version**
3.8m

**Logs**
[crash-2020-08-10_18.23.53-server.txt](https://github.com/ldtteam/Performant/files/5052729/crash-2020-08-10_18.23.53-server.txt)

**Comment by someaddons** [comment]
should be fixed in 3.9
