### ISSUE TITLE
Server doesn't start

### ISSUE THREAD

**Issue by lebanni** [ldtteam/Performant#72]
forge-1.15.2-31.2.36.jar
performant-1.15-3.10m.jar
MixinBootstrap-1.0.3.jar

java : openjdk version "11.0.8"

The server doesn't complete the starting procedure and the console doesn't respond.
performant-1.15-3.9m.jar has the same problem.
I tried with java openjdk version "1.8.0_265" and have the same issue.
performant-1.15-3.8m.jar is still working fine.

[latest.log](https://github.com/ldtteam/Performant/files/5068753/latest.log)

**Comment by someaddons** [comment]
thats an incompat with lithium, can just remove that one its not getting any updates anymore
