### ISSUE TITLE
Server crash on ticking entity

### ISSUE THREAD

**Issue by phyne** [ldtteam/Performant#8]
**Describe the bug**
The server crashes when the game/mod ticks a skeleton trap horse. I don't know if it is this mod, but I don't know where else to start. The server crashed one more time when players attempted to reconnect, but on a third try I was able to get in, and I removed all skeleton_horse entities.

**To Reproduce**
A player reported lightning striking, and then the server immediately crashing. Upon checking the crash-report, it looks like the game was ticking a skeleton horse, and performant is mentioned in the log. 

/summon minecraft:skeleton_horse ~ ~ ~ {SkeletonTrap:1b}

A normal skeleton_horse doesn't cause a crash.

**Mod version**
performant-1.14.4-1.4.jar

**Logs**
[crash-log](https://gist.github.com/phyne/547bd5211f11812712db312b416a41ae)

**Comment by someaddons** [comment]
fixed in 1.5
