### ISSUE TITLE
Multiplayer server crashes loading chunks

### ISSUE THREAD

**Issue by dreckz** [ldtteam/Performant#9]
**Describe the bug**
Whilst flying around and loading chunks with about 2-3 other people, the server ends up freezing and times out.  One of the other players may have done something different, but this is to my knowledge.
**To Reproduce**
1. Go fly and around to produce chunks
2. Game freezes randomly
3. See error

**Expected behavior**
Should just generate chunks like normal
** Mod version **
Your mods version
1.5

** Logs **
Latest/Crash log
[crash-2020-01-21_04.19.44-server.txt](https://github.com/ldtteam/Performant/files/4090720/crash-2020-01-21_04.19.44-server.txt)

**Comment by someaddons** [comment]
this is completly normal vanilla behaviour, chunk generation is an expensive task and when you're flying around with multiple ppl, generating chunks and it lags it simply means that your server cannot keep up with generating the chunks fast enough. Look into pre-generating chunks if you wan to solve this, its not a bug.
